name: base
channels:
  - defaults
dependencies:
  - python=3.8
  - pip:
      - cloudpickle==3.0.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - jupyter_client==8.6.0
      - jupyter_core==5.5.0
      - jupyterlab-widgets==3.0.9
      - jupyterlab_pygments==0.3.0
      - matplotlib==3.6.0
      - matplotlib-inline==0.1.6
      - numpy==1.25.2
      - pandas==1.5.3
      - pytest==7.1.3
      - pytest-cov==4.0.0
      - python-dotenv==0.21.0
      - scikit-base==0.5.2
      - scikit-learn==1.3.2
      - scikit-plot==0.3.7
      - scipy==1.10.1
      - Scrapy==2.11.0
      - seaborn==0.13.0
      - stack-data==0.6.3
      - statsmodels==0.14.1
            